apiVersion: v1
kind: Namespace
metadata:
  name: monitoring2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic
  namespace: monitoring2
spec:
  url: https://helm.elastic.co
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: monitoring2
spec:
  interval: 10m
  chart:
    spec:
      chart: elasticsearch
      # version: "7.17.3"   # pin version
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: monitoring2
  values:
    replicas: 1
    minimumMasterNodes: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: monitoring2
spec:
  interval: 10m
  chart:
    spec:
      chart: kibana
      # version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: monitoring2
  values:
    service:
      type: ClusterIP # or NodePort if no LB
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logstash
  namespace: monitoring2
spec:
  interval: 10m
  chart:
    spec:
      chart: logstash
      # version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: monitoring2
  values:
    replicas: 1
