apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prom
  namespace: monitoring
spec:
  url: oci://ghcr.io/prometheus-community/charts
  type: oci
---
apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
stringData:
  additional-scrape-configs.yaml: |
    - job_name: "podinfo"
      static_configs:
        - targets: ["10.96.61.56:9898"]
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prom
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prom
      interval: 1h
  values:
    additionalScrapeConfigsSecret:
      enable: true
      name: additional-scrape-configs
      key: additional-scrape-configs.yaml
