apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 2m
  path: ./prom-grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system