apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loki
  namespace: monitoring
spec:
  url: https://grafana.github.io/helm-charts
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: monitoring
  values:
    grafana:
      enabled: true

    loki:
      image:
        tag: 2.6.1
      service:
        type: NodePort
        nodePort: 31100

    prometheus:
      enabled: true

    promtail:
      enabled: true
      config:
        scrape_configs:
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
          - role: pod
          pipeline_stages:
          - cri: {}
          relabel_configs:
          - action: replace
            source_labels: [ __meta_kubernetes_namespace ]
            target_label: namespace
          - action: replace
            source_labels: [ __meta_kubernetes_pod_name ]
            target_label: pod
          - action: replace
            source_labels: [ __meta_kubernetes_pod_container_name ]
            target_label: container
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels: [ __meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name ]
            target_label: __path__
