apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loki
  namespace: monitoring
spec:
  url: https://grafana.github.io/helm-charts
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: monitoring
  values:
    grafana:
      enabled: true

    loki:
      image:
        tag: 2.6.1

    prometheus:
      enabled: true

    promtail:
      enabled: true
      config:
        scrape_configs:
        - job_name: kubernetes-pods-podinfo
          kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
              - podinfo
          pipeline_stages:
          - docker: {}
          relabel_configs:
          - source_labels: [ __meta_kubernetes_namespace ]
            target_label: namespace
          - source_labels: [ __meta_kubernetes_pod_name ]
            target_label: pod
          - source_labels: [ __meta_kubernetes_container_name ]
            target_label: container
